### ISSUE TITLE
 Conversation Id is red, error uploading file 

### ISSUE THREAD

**Issue by tatarco** [nmazuz/Jobee-LinkedIn-Job-Search-Assistant#1]
when attempting to use i'm getting a red dot on comversation id, the  upload button seems to be grey but is enabled, attemp to upload results in an error
<img width="355" alt="Screenshot 2024-02-17 at 7 36 00" src="https://github.com/nmazuz/Jobee-LinkedIn-Job-Search-Assistant/assets/39020298/a4a0cb08-d8fe-4390-b2a4-bf0fec326790">

**Comment by nmazuz** [comment]
Hi @tatarco 

When installing the plugin on the first time, it makes a request to chatGPT to create new conversation.
Sometimes, the free version of chatGPT is not available so this request failed.
You can try to re-install the extension and probably it will fix the problem.

<img width="768" alt="image" src="https://github.com/nmazuz/Jobee-LinkedIn-Job-Search-Assistant/assets/2725276/51362b5c-2bb1-443e-b3a0-94f0fc1e685e">

**Comment by tatarco** [comment]
Thank you, I’ll add a commit to your readme

**Comment by barak3d** [comment]
Same problem for me, getting an error (500) when `https://resumatch-rqthba6dyq-zf.a.run.app/new` is sent. 
Tried reloading the ext/reinstalling several times, this API keeps failing (checked in service worker devtool).
Starting a new session in ChatGPT manually works.

Error:
```
"An unexpected error occurred. Error message: 'NoneType' object is not subscriptable.\nThis is what the server returned: {\"wss_url\":\"wss://chatgpt-async-webps-prod-southcentralus-1.webpubsub.azure.com/client/hubs/conversations?access_token=xxx\",\"expires_at\":\"2024-02-19T22:45:51.364823+00:00\",\"conversation_id\":\"xxx\",\"response_id\":\"xxx-MRS\"}."

**Comment by GadAHRN** [comment]
I also getting a red dot on comversation id (after reinstalling), with this error message:

Error sending to server: TypeError: Cannot read properties of null (reading 'conversation_id')
80         .catch(error => console.error('Error sending to server:', error));

**Comment by nmazuz** [comment]
1. Please make sure your chatGPT session is valid (you can chat in chatGPT UI)
2. Sometimes, chatGPT has temporary issues who can fail the first conversation creation.
3. After you make sure that chatGPT UI is working properly, try to reinstall the extension
